#pragma once
namespace VX {
	class script {
	public:
		void detach();
	};
	script* GetScript();

	inline const char* array_example[] = {
	"Place Holder 1",
	"Place Holder 2",
	"Place Holder 3"
	};
	inline int array_position_example;
	inline float number_example;
	inline bool bool_example;
	inline int m_selected_vehicle_class;

	void main_script();
	void home_submenu();
	void self_submenu();
	void Self_Animation();
	void Self_models();
	void Self_vision();
	void Self_handtrails();
	void Self_particles();
	void Self_water();
	void Self_outfits();
	void Self_loadoutfits();
	void Vehicle_submenu();
	void Vehicle_lossantoscustom();
	void Vehicle_colorprimary();
	void Vehicle_colorsecondary();
	void Vehicle_lights();
	void Vehicle_loadVehicle();
	void Vehicle_custom();
	void Vehicle_performance();
	void PlayerList_overseer();
	void Vehicle_ramps();
	void Teleport_submenu();
	void Teleport_loadteleport();
	void PlayerList_Friendly();
	void PlayerList_vehicle();
	void PlayerList_evil();
	void Self_movement();
	void Weapon_submenu();
	void Weapon_tints();
	void Weapon_paint();
	void Weapon_gravity();
	void Weapon_Object();
	void Weapon_magnet();
	void Weapon_laser();
	void Vehicle_acrobatics();
	void Vehicle_fly();
	void Vehicle_general();
	void Vehicle_particle();
	void Misc_submenu();
	void Misc_train();
	void Misc_clouds();
	void Misc_mapcolor();
	void Misc_times();
	void Misc_strorymode();
	void Misc_traffic();
	void Misc_weather();
	void Self_general();
	void Teleport_outdoors();
	void Teleport_indoors();
	void Teleport_lossantoscustom();
	void Teleport_clotheshop();
	void Teleport_airport();
	void Teleport_ammunation();
	void Teleport_barbershop();
	void Teleport_tatooshop();
	void Teleport_store();
	void Recovery_submenu();
	void Recovery_money();
	void Recovery_rp();
	void Recovery_increase();
	void Recovery_stats();
	void Recovery_unlocks();
	void Protection_submenu();
	void Spawner_submenu();
	void Spawner_object();
	void Spawner_settings();
	void Settings_general();
	void Settings_credit();
	void Settings_theme();
	void settings_footer_submenu_sprite_color();
	void settings_header_text_color();
	void toggle_color();
	void break_color();
	void option_color();
	void sub_color();
	void selected_player_submenu();
	void player_submenu();
	void settings_submenu();
	void settings_options_submenu();
	void settings_header_submenu();
	void settings_submenu_submenu();
	void settings_footer_submenu();
	void settings_footer_submenu_bg_color();
	void settings_options_text_color();
	void settings_header_bg_color();
	void settings_playerinfo_submenu();
	void spawner_submenu();
	void spawner_vehicle_submenu();
	void demo_submenu();
	void tab_custom();
	void Network_submenu();
	void ScriptHookV_Submenu();
	void Download_ScriptHookV_Submenu();
	void Network_sessionfinder();
	void Network_spoofer();
	void Network_esp();
	void Weapon_weapons();
	void Weapon_melee();
	void Weapon_pistol();
	void Weapon_submachineguns();
	void Weapon_shotguns();
	void Weapon_ar();
	void Weapon_mg();
	void Weapon_spr();
	void Weapon_heavy();
	void Weapon_th();
	void Weapon_misc();
	void Spawner_mapmods();
	void Spawner_xml();
	void draw_animated_header();
	inline bool preview_toggle = false;
}