


namespace VX
{
	enum class eControllerInputs : int32_t {
		INPUT_EMPTY = -1,
		INPUT_NEXT_CAMERA,
		INPUT_LOOK_LR,
		INPUT_LOOK_UD,
		INPUT_LOOK_UP_ONLY,
		INPUT_LOOK_DOWN_ONLY,
		INPUT_LOOK_LEFT_ONLY,
		INPUT_LOOK_RIGHT_ONLY,
		INPUT_CINEMATIC_SLOWMO,
		INPUT_SCRIPTED_FLY_UD,
		INPUT_SCRIPTED_FLY_LR,
		INPUT_SCRIPTED_FLY_ZUP,
		INPUT_SCRIPTED_FLY_ZDOWN,
		INPUT_WEAPON_WHEEL_UD,
		INPUT_WEAPON_WHEEL_LR,
		INPUT_WEAPON_WHEEL_NEXT,
		INPUT_WEAPON_WHEEL_PREV,
		INPUT_SELECT_NEXT_WEAPON,
		INPUT_SELECT_PREV_WEAPON,
		INPUT_SKIP_CUTSCENE,
		INPUT_CHARACTER_WHEEL,
		INPUT_MULTIPLAYER_INFO,
		INPUT_SPRINT,
		INPUT_JUMP,
		INPUT_ENTER,
		INPUT_ATTACK,
		INPUT_AIM,
		INPUT_LOOK_BEHIND,
		INPUT_PHONE,
		INPUT_SPECIAL_ABILITY,
		INPUT_SPECIAL_ABILITY_SECONDARY,
		INPUT_MOVE_LR,
		INPUT_MOVE_UD,
		INPUT_MOVE_UP_ONLY,
		INPUT_MOVE_DOWN_ONLY,
		INPUT_MOVE_LEFT_ONLY,
		INPUT_MOVE_RIGHT_ONLY,
		INPUT_DUCK,
		INPUT_SELECT_WEAPON,
		INPUT_PICKUP,
		INPUT_SNIPER_ZOOM,
		INPUT_SNIPER_ZOOM_IN_ONLY,
		INPUT_SNIPER_ZOOM_OUT_ONLY,
		INPUT_SNIPER_ZOOM_IN_SECONDARY,
		INPUT_SNIPER_ZOOM_OUT_SECONDARY,
		INPUT_COVER,
		INPUT_RELOAD,
		INPUT_TALK,
		INPUT_DETONATE,
		INPUT_HUD_SPECIAL,
		INPUT_ARREST,
		INPUT_ACCURATE_AIM,
		INPUT_CONTEXT,
		INPUT_CONTEXT_SECONDARY,
		INPUT_WEAPON_SPECIAL,
		INPUT_WEAPON_SPECIAL_TWO,
		INPUT_DIVE,
		INPUT_DROP_WEAPON,
		INPUT_DROP_AMMO,
		INPUT_THROW_GRENADE,
		INPUT_VEH_MOVE_LR,
		INPUT_VEH_MOVE_UD,
		INPUT_VEH_MOVE_UP_ONLY,
		INPUT_VEH_MOVE_DOWN_ONLY,
		INPUT_VEH_MOVE_LEFT_ONLY,
		INPUT_VEH_MOVE_RIGHT_ONLY,
		INPUT_VEH_SPECIAL,
		INPUT_VEH_GUN_LR,
		INPUT_VEH_GUN_UD,
		INPUT_VEH_AIM,
		INPUT_VEH_ATTACK,
		INPUT_VEH_ATTACK2,
		INPUT_VEH_ACCELERATE,
		INPUT_VEH_BRAKE,
		INPUT_VEH_DUCK,
		INPUT_VEH_HEADLIGHT,
		INPUT_VEH_EXIT,
		INPUT_VEH_HANDBRAKE,
		INPUT_VEH_HOTWIRE_LEFT,
		INPUT_VEH_HOTWIRE_RIGHT,
		INPUT_VEH_LOOK_BEHIND,
		INPUT_VEH_CIN_CAM,
		INPUT_VEH_NEXT_RADIO,
		INPUT_VEH_PREV_RADIO,
		INPUT_VEH_NEXT_RADIO_TRACK,
		INPUT_VEH_PREV_RADIO_TRACK,
		INPUT_VEH_RADIO_WHEEL,
		INPUT_VEH_HORN,
		INPUT_VEH_FLY_THROTTLE_UP,
		INPUT_VEH_FLY_THROTTLE_DOWN,
		INPUT_VEH_FLY_YAW_LEFT,
		INPUT_VEH_FLY_YAW_RIGHT,
		INPUT_VEH_PASSENGER_AIM,
		INPUT_VEH_PASSENGER_ATTACK,
		INPUT_VEH_SPECIAL_ABILITY_FRANKLIN,
		INPUT_VEH_STUNT_UD,
		INPUT_VEH_CINEMATIC_UD,
		INPUT_VEH_CINEMATIC_UP_ONLY,
		INPUT_VEH_CINEMATIC_DOWN_ONLY,
		INPUT_VEH_CINEMATIC_LR,
		INPUT_VEH_SELECT_NEXT_WEAPON,
		INPUT_VEH_SELECT_PREV_WEAPON,
		INPUT_VEH_ROOF,
		INPUT_VEH_JUMP,
		INPUT_VEH_GRAPPLING_HOOK,
		INPUT_VEH_SHUFFLE,
		INPUT_VEH_DROP_PROJECTILE,
		INPUT_VEH_MOUSE_CONTROL_OVERRIDE,
		INPUT_VEH_FLY_ROLL_LR,
		INPUT_VEH_FLY_ROLL_LEFT_ONLY,
		INPUT_VEH_FLY_ROLL_RIGHT_ONLY,
		INPUT_VEH_FLY_PITCH_UD,
		INPUT_VEH_FLY_PITCH_UP_ONLY,
		INPUT_VEH_FLY_PITCH_DOWN_ONLY,
		INPUT_VEH_FLY_UNDERCARRIAGE,
		INPUT_VEH_FLY_ATTACK,
		INPUT_VEH_FLY_SELECT_NEXT_WEAPON,
		INPUT_VEH_FLY_SELECT_PREV_WEAPON,
		INPUT_VEH_FLY_SELECT_TARGET_LEFT,
		INPUT_VEH_FLY_SELECT_TARGET_RIGHT,
		INPUT_VEH_FLY_VERTICAL_FLIGHT_MODE,
		INPUT_VEH_FLY_DUCK,
		INPUT_VEH_FLY_ATTACK_CAMERA,
		INPUT_VEH_FLY_MOUSE_CONTROL_OVERRIDE,
		INPUT_VEH_SUB_TURN_LR,
		INPUT_VEH_SUB_TURN_LEFT_ONLY,
		INPUT_VEH_SUB_TURN_RIGHT_ONLY,
		INPUT_VEH_SUB_PITCH_UD,
		INPUT_VEH_SUB_PITCH_UP_ONLY,
		INPUT_VEH_SUB_PITCH_DOWN_ONLY,
		INPUT_VEH_SUB_THROTTLE_UP,
		INPUT_VEH_SUB_THROTTLE_DOWN,
		INPUT_VEH_SUB_ASCEND,
		INPUT_VEH_SUB_DESCEND,
		INPUT_VEH_SUB_TURN_HARD_LEFT,
		INPUT_VEH_SUB_TURN_HARD_RIGHT,
		INPUT_VEH_SUB_MOUSE_CONTROL_OVERRIDE,
		INPUT_VEH_PUSHBIKE_PEDAL,
		INPUT_VEH_PUSHBIKE_SPRINT,
		INPUT_VEH_PUSHBIKE_FRONT_BRAKE,
		INPUT_VEH_PUSHBIKE_REAR_BRAKE,
		INPUT_MELEE_ATTACK_LIGHT,
		INPUT_MELEE_ATTACK_HEAVY,
		INPUT_MELEE_ATTACK_ALTERNATE,
		INPUT_MELEE_BLOCK,
		INPUT_PARACHUTE_DEPLOY,
		INPUT_PARACHUTE_DETACH,
		INPUT_PARACHUTE_TURN_LR,
		INPUT_PARACHUTE_TURN_LEFT_ONLY,
		INPUT_PARACHUTE_TURN_RIGHT_ONLY,
		INPUT_PARACHUTE_PITCH_UD,
		INPUT_PARACHUTE_PITCH_UP_ONLY,
		INPUT_PARACHUTE_PITCH_DOWN_ONLY,
		INPUT_PARACHUTE_BRAKE_LEFT,
		INPUT_PARACHUTE_BRAKE_RIGHT,
		INPUT_PARACHUTE_SMOKE,
		INPUT_PARACHUTE_PRECISION_LANDING,
		INPUT_MAP,
		INPUT_SELECT_WEAPON_UNARMED,
		INPUT_SELECT_WEAPON_MELEE,
		INPUT_SELECT_WEAPON_HANDGUN,
		INPUT_SELECT_WEAPON_SHOTGUN,
		INPUT_SELECT_WEAPON_SMG,
		INPUT_SELECT_WEAPON_AUTO_RIFLE,
		INPUT_SELECT_WEAPON_SNIPER,
		INPUT_SELECT_WEAPON_HEAVY,
		INPUT_SELECT_WEAPON_SPECIAL,
		INPUT_SELECT_CHARACTER_MICHAEL,
		INPUT_SELECT_CHARACTER_FRANKLIN,
		INPUT_SELECT_CHARACTER_TREVOR,
		INPUT_SELECT_CHARACTER_MULTIPLAYER,
		INPUT_SAVE_REPLAY_CLIP,
		INPUT_SPECIAL_ABILITY_PC,
		INPUT_CELLPHONE_UP,
		INPUT_CELLPHONE_DOWN,
		INPUT_CELLPHONE_LEFT,
		INPUT_CELLPHONE_RIGHT,
		INPUT_CELLPHONE_SELECT,
		INPUT_CELLPHONE_CANCEL,
		INPUT_CELLPHONE_OPTION,
		INPUT_CELLPHONE_EXTRA_OPTION,
		INPUT_CELLPHONE_SCROLL_FORWARD,
		INPUT_CELLPHONE_SCROLL_BACKWARD,
		INPUT_CELLPHONE_CAMERA_FOCUS_LOCK,
		INPUT_CELLPHONE_CAMERA_GRID,
		INPUT_CELLPHONE_CAMERA_SELFIE,
		INPUT_CELLPHONE_CAMERA_DOF,
		INPUT_CELLPHONE_CAMERA_EXPRESSION,
		INPUT_FRONTEND_DOWN,
		INPUT_FRONTEND_UP,
		INPUT_FRONTEND_LEFT,
		INPUT_FRONTEND_RIGHT,
		INPUT_FRONTEND_RDOWN,
		INPUT_FRONTEND_RUP,
		INPUT_FRONTEND_RLEFT,
		INPUT_FRONTEND_RRIGHT,
		INPUT_FRONTEND_AXIS_X,
		INPUT_FRONTEND_AXIS_Y,
		INPUT_FRONTEND_RIGHT_AXIS_X,
		INPUT_FRONTEND_RIGHT_AXIS_Y,
		INPUT_FRONTEND_PAUSE,
		INPUT_FRONTEND_PAUSE_ALTERNATE,
		INPUT_FRONTEND_ACCEPT,
		INPUT_FRONTEND_CANCEL,
		INPUT_FRONTEND_X,
		INPUT_FRONTEND_Y,
		INPUT_FRONTEND_LB,
		INPUT_FRONTEND_RB,
		INPUT_FRONTEND_LT,
		INPUT_FRONTEND_RT,
		INPUT_FRONTEND_LS,
		INPUT_FRONTEND_RS,
		INPUT_FRONTEND_LEADERBOARD,
		INPUT_FRONTEND_SOCIAL_CLUB,
		INPUT_FRONTEND_SOCIAL_CLUB_SECONDARY,
		INPUT_FRONTEND_DELETE,
		INPUT_FRONTEND_ENDSCREEN_ACCEPT,
		INPUT_FRONTEND_ENDSCREEN_EXPAND,
		INPUT_FRONTEND_SELECT,
		INPUT_SCRIPT_LEFT_AXIS_X,
		INPUT_SCRIPT_LEFT_AXIS_Y,
		INPUT_SCRIPT_RIGHT_AXIS_X,
		INPUT_SCRIPT_RIGHT_AXIS_Y,
		INPUT_SCRIPT_RUP,
		INPUT_SCRIPT_RDOWN,
		INPUT_SCRIPT_RLEFT,
		INPUT_SCRIPT_RRIGHT,
		INPUT_SCRIPT_LB,
		INPUT_SCRIPT_RB,
		INPUT_SCRIPT_LT,
		INPUT_SCRIPT_RT,
		INPUT_SCRIPT_LS,
		INPUT_SCRIPT_RS,
		INPUT_SCRIPT_PAD_UP,
		INPUT_SCRIPT_PAD_DOWN,
		INPUT_SCRIPT_PAD_LEFT,
		INPUT_SCRIPT_PAD_RIGHT,
		INPUT_SCRIPT_SELECT,
		INPUT_CURSOR_ACCEPT,
		INPUT_CURSOR_CANCEL,
		INPUT_CURSOR_X,
		INPUT_CURSOR_Y,
		INPUT_CURSOR_SCROLL_UP,
		INPUT_CURSOR_SCROLL_DOWN,
		INPUT_ENTER_CHEAT_CODE,
		INPUT_INTERACTION_MENU,
		INPUT_MP_TEXT_CHAT_ALL,
		INPUT_MP_TEXT_CHAT_TEAM,
		INPUT_MP_TEXT_CHAT_FRIENDS,
		INPUT_MP_TEXT_CHAT_CREW,
		INPUT_PUSH_TO_TALK,
		INPUT_CREATOR_LS,
		INPUT_CREATOR_RS,
		INPUT_CREATOR_LT,
		INPUT_CREATOR_RT,
		INPUT_CREATOR_MENU_TOGGLE,
		INPUT_CREATOR_ACCEPT,
		INPUT_CREATOR_DELETE,
		INPUT_ATTACK2,
		INPUT_RAPPEL_JUMP,
		INPUT_RAPPEL_LONG_JUMP,
		INPUT_RAPPEL_SMASH_WINDOW,
		INPUT_PREV_WEAPON,
		INPUT_NEXT_WEAPON,
		INPUT_MELEE_ATTACK1,
		INPUT_MELEE_ATTACK2,
		INPUT_WHISTLE,
		INPUT_MOVE_LEFT,
		INPUT_MOVE_RIGHT,
		INPUT_MOVE_UP,
		INPUT_MOVE_DOWN,
		INPUT_LOOK_LEFT,
		INPUT_LOOK_RIGHT,
		INPUT_LOOK_UP,
		INPUT_LOOK_DOWN,
		INPUT_SNIPER_ZOOM_IN,
		INPUT_SNIPER_ZOOM_OUT,
		INPUT_SNIPER_ZOOM_IN_ALTERNATE,
		INPUT_SNIPER_ZOOM_OUT_ALTERNATE,
		INPUT_VEH_MOVE_LEFT,
		INPUT_VEH_MOVE_RIGHT,
		INPUT_VEH_MOVE_UP,
		INPUT_VEH_MOVE_DOWN,
		INPUT_VEH_GUN_LEFT,
		INPUT_VEH_GUN_RIGHT,
		INPUT_VEH_GUN_UP,
		INPUT_VEH_GUN_DOWN,
		INPUT_VEH_LOOK_LEFT,
		INPUT_VEH_LOOK_RIGHT,
		INPUT_REPLAY_START_STOP_RECORDING,
		INPUT_REPLAY_START_STOP_RECORDING_SECONDARY,
		INPUT_SCALED_LOOK_LR,
		INPUT_SCALED_LOOK_UD,
		INPUT_SCALED_LOOK_UP_ONLY,
		INPUT_SCALED_LOOK_DOWN_ONLY,
		INPUT_SCALED_LOOK_LEFT_ONLY,
		INPUT_SCALED_LOOK_RIGHT_ONLY,
		INPUT_REPLAY_MARKER_DELETE,
		INPUT_REPLAY_CLIP_DELETE,
		INPUT_REPLAY_PAUSE,
		INPUT_REPLAY_REWIND,
		INPUT_REPLAY_FFWD,
		INPUT_REPLAY_NEWMARKER,
		INPUT_REPLAY_RECORD,
		INPUT_REPLAY_SCREENSHOT,
		INPUT_REPLAY_HIDEHUD,
		INPUT_REPLAY_STARTPOINT,
		INPUT_REPLAY_ENDPOINT,
		INPUT_REPLAY_ADVANCE,
		INPUT_REPLAY_BACK,
		INPUT_REPLAY_TOOLS,
		INPUT_REPLAY_RESTART,
		INPUT_REPLAY_SHOWHOTKEY,
		INPUT_REPLAY_CYCLEMARKERLEFT,
		INPUT_REPLAY_CYCLEMARKERRIGHT,
		INPUT_REPLAY_FOVINCREASE,
		INPUT_REPLAY_FOVDECREASE,
		INPUT_REPLAY_CAMERAUP,
		INPUT_REPLAY_CAMERADOWN,
		INPUT_REPLAY_SAVE,
		INPUT_REPLAY_TOGGLETIME,
		INPUT_REPLAY_TOGGLETIPS,
		INPUT_REPLAY_PREVIEW,
		INPUT_REPLAY_TOGGLE_TIMELINE,
		INPUT_REPLAY_TIMELINE_PICKUP_CLIP,
		INPUT_REPLAY_TIMELINE_DUPLICATE_CLIP,
		INPUT_REPLAY_TIMELINE_PLACE_CLIP,
		INPUT_REPLAY_CTRL,
		INPUT_REPLAY_TIMELINE_SAVE,
		INPUT_REPLAY_PREVIEW_AUDIO,
		INPUT_VEH_DRIVE_LOOK,
		INPUT_VEH_DRIVE_LOOK2,
		INPUT_VEH_FLY_ATTACK2,
		INPUT_RADIO_WHEEL_UD,
		INPUT_RADIO_WHEEL_LR,
		INPUT_VEH_SLOWMO_UD,
		INPUT_VEH_SLOWMO_UP_ONLY,
		INPUT_VEH_SLOWMO_DOWN_ONLY,
		INPUT_VEH_HYDRAULICS_CONTROL_TOGGLE,
		INPUT_VEH_HYDRAULICS_CONTROL_LEFT,
		INPUT_VEH_HYDRAULICS_CONTROL_RIGHT,
		INPUT_VEH_HYDRAULICS_CONTROL_UP,
		INPUT_VEH_HYDRAULICS_CONTROL_DOWN,
		INPUT_VEH_HYDRAULICS_CONTROL_LR,
		INPUT_VEH_HYDRAULICS_CONTROL_UD,
		INPUT_SWITCH_VISOR,
		INPUT_VEH_MELEE_HOLD,
		INPUT_VEH_MELEE_LEFT,
		INPUT_VEH_MELEE_RIGHT,
		INPUT_MAP_POI,
		INPUT_REPLAY_SNAPMATIC_PHOTO,
		INPUT_VEH_CAR_JUMP,
		INPUT_VEH_ROCKET_BOOST,
		INPUT_VEH_FLY_BOOST,
		INPUT_VEH_PARACHUTE,
		INPUT_VEH_BIKE_WINGS,
		INPUT_VEH_FLY_BOMB_BAY,
		INPUT_VEH_FLY_COUNTER,
		INPUT_VEH_TRANSFORM,
		MAX_INPUTS,
		UNDEFINED_INPUT,
		DYNAMIC_MAPPING_MOUSE_X,
		DYNAMIC_MAPPING_MOUSE_Y,
		FIRST_INPUT,
		SCRIPTED_INPUT_FIRST,
		SCRIPTED_INPUT_LAST
	};
	enum eControls {
		ControlNextCamera = 0,
		ControlLookLeftRight = 1,
		ControlLookUpDown = 2,
		ControlLookUpOnly = 3,
		ControlLookDownOnly = 4,
		ControlLookLeftOnly = 5,
		ControlLookRightOnly = 6,
		ControlCinematicSlowMo = 7,
		ControlFlyUpDown = 8,
		ControlFlyLeftRight = 9,
		ControlScriptedFlyZUp = 10,
		ControlScriptedFlyZDown = 11,
		ControlWeaponWheelUpDown = 12,
		ControlWeaponWheelLeftRight = 13,
		ControlWeaponWheelNext = 14,
		ControlWeaponWheelPrev = 15,
		ControlSelectNextWeapon = 16,
		ControlSelectPrevWeapon = 17,
		ControlSkipCutscene = 18,
		ControlCharacterWheel = 19,
		ControlMultiplayerInfo = 20,
		ControlSprint = 21,
		ControlJump = 22,
		ControlEnter = 23,
		ControlAttack = 24,
		ControlAim = 25,
		ControlLookBehind = 26,
		ControlPhone = 27,
		ControlSpecialAbility = 28,
		ControlSpecialAbilitySecondary = 29,
		ControlMoveLeftRight = 30,
		ControlMoveUpDown = 31,
		ControlMoveUpOnly = 32,
		ControlMoveDownOnly = 33,
		ControlMoveLeftOnly = 34,
		ControlMoveRightOnly = 35,
		ControlDuck = 36,
		ControlSelectWeapon = 37,
		ControlPickup = 38,
		ControlSniperZoom = 39,
		ControlSniperZoomInOnly = 40,
		ControlSniperZoomOutOnly = 41,
		ControlSniperZoomInSecondary = 42,
		ControlSniperZoomOutSecondary = 43,
		ControlCover = 44,
		ControlReload = 45,
		ControlTalk = 46,
		ControlDetonate = 47,
		ControlHUDSpecial = 48,
		ControlArrest = 49,
		ControlAccurateAim = 50,
		ControlContext = 51,
		ControlContextSecondary = 52,
		ControlWeaponSpecial = 53,
		ControlWeaponSpecial2 = 54,
		ControlDive = 55,
		ControlDropWeapon = 56,
		ControlDropAmmo = 57,
		ControlThrowGrenade = 58,
		ControlVehicleMoveLeftRight = 59,
		ControlVehicleMoveUpDown = 60,
		ControlVehicleMoveUpOnly = 61,
		ControlVehicleMoveDownOnly = 62,
		ControlVehicleMoveLeftOnly = 63,
		ControlVehicleMoveRightOnly = 64,
		ControlVehicleSpecial = 65,
		ControlVehicleGunLeftRight = 66,
		ControlVehicleGunUpDown = 67,
		ControlVehicleAim = 68,
		ControlVehicleAttack = 69,
		ControlVehicleAttack2 = 70,
		ControlVehicleAccelerate = 71,
		ControlVehicleBrake = 72,
		ControlVehicleDuck = 73,
		ControlVehicleHeadlight = 74,
		ControlVehicleExit = 75,
		ControlVehicleHandbrake = 76,
		ControlVehicleHotwireLeft = 77,
		ControlVehicleHotwireRight = 78,
		ControlVehicleLookBehind = 79,
		ControlVehicleCinCam = 80,
		ControlVehicleNextRadio = 81,
		ControlVehiclePrevRadio = 82,
		ControlVehicleNextRadioTrack = 83,
		ControlVehiclePrevRadioTrack = 84,
		ControlVehicleRadioWheel = 85,
		ControlVehicleHorn = 86,
		ControlVehicleFlyThrottleUp = 87,
		ControlVehicleFlyThrottleDown = 88,
		ControlVehicleFlyYawLeft = 89,
		ControlVehicleFlyYawRight = 90,
		ControlVehiclePassengerAim = 91,
		ControlVehiclePassengerAttack = 92,
		ControlVehicleSpecialAbilityFranklin = 93,
		ControlVehicleStuntUpDown = 94,
		ControlVehicleCinematicUpDown = 95,
		ControlVehicleCinematicUpOnly = 96,
		ControlVehicleCinematicDownOnly = 97,
		ControlVehicleCinematicLeftRight = 98,
		ControlVehicleSelectNextWeapon = 99,
		ControlVehicleSelectPrevWeapon = 100,
		ControlVehicleRoof = 101,
		ControlVehicleJump = 102,
		ControlVehicleGrapplingHook = 103,
		ControlVehicleShuffle = 104,
		ControlVehicleDropProjectile = 105,
		ControlVehicleMouseControlOverride = 106,
		ControlVehicleFlyRollLeftRight = 107,
		ControlVehicleFlyRollLeftOnly = 108,
		ControlVehicleFlyRollRightOnly = 109,
		ControlVehicleFlyPitchUpDown = 110,
		ControlVehicleFlyPitchUpOnly = 111,
		ControlVehicleFlyPitchDownOnly = 112,
		ControlVehicleFlyUnderCarriage = 113,
		ControlVehicleFlyAttack = 114,
		ControlVehicleFlySelectNextWeapon = 115,
		ControlVehicleFlySelectPrevWeapon = 116,
		ControlVehicleFlySelectTargetLeft = 117,
		ControlVehicleFlySelectTargetRight = 118,
		ControlVehicleFlyVerticalFlightMode = 119,
		ControlVehicleFlyDuck = 120,
		ControlVehicleFlyAttackCamera = 121,
		ControlVehicleFlyMouseControlOverride = 122,
		ControlVehicleSubTurnLeftRight = 123,
		ControlVehicleSubTurnLeftOnly = 124,
		ControlVehicleSubTurnRightOnly = 125,
		ControlVehicleSubPitchUpDown = 126,
		ControlVehicleSubPitchUpOnly = 127,
		ControlVehicleSubPitchDownOnly = 128,
		ControlVehicleSubThrottleUp = 129,
		ControlVehicleSubThrottleDown = 130,
		ControlVehicleSubAscend = 131,
		ControlVehicleSubDescend = 132,
		ControlVehicleSubTurnHardLeft = 133,
		ControlVehicleSubTurnHardRight = 134,
		ControlVehicleSubMouseControlOverride = 135,
		ControlVehiclePushbikePedal = 136,
		ControlVehiclePushbikeSprint = 137,
		ControlVehiclePushbikeFrontBrake = 138,
		ControlVehiclePushbikeRearBrake = 139,
		ControlMeleeAttackLight = 140,
		ControlMeleeAttackHeavy = 141,
		ControlMeleeAttackAlternate = 142,
		ControlMeleeBlock = 143,
		ControlParachuteDeploy = 144,
		ControlParachuteDetach = 145,
		ControlParachuteTurnLeftRight = 146,
		ControlParachuteTurnLeftOnly = 147,
		ControlParachuteTurnRightOnly = 148,
		ControlParachutePitchUpDown = 149,
		ControlParachutePitchUpOnly = 150,
		ControlParachutePitchDownOnly = 151,
		ControlParachuteBrakeLeft = 152,
		ControlParachuteBrakeRight = 153,
		ControlParachuteSmoke = 154,
		ControlParachutePrecisionLanding = 155,
		ControlMap = 156,
		ControlSelectWeaponUnarmed = 157,
		ControlSelectWeaponMelee = 158,
		ControlSelectWeaponHandgun = 159,
		ControlSelectWeaponShotgun = 160,
		ControlSelectWeaponSmg = 161,
		ControlSelectWeaponAutoRifle = 162,
		ControlSelectWeaponSniper = 163,
		ControlSelectWeaponHeavy = 164,
		ControlSelectWeaponSpecial = 165,
		ControlSelectCharacterMichael = 166,
		ControlSelectCharacterFranklin = 167,
		ControlSelectCharacterTrevor = 168,
		ControlSelectCharacterMultiplayer = 169,
		ControlSaveReplayClip = 170,
		ControlSpecialAbilityPC = 171,
		ControlPhoneUp = 172,
		ControlPhoneDown = 173,
		ControlPhoneLeft = 174,
		ControlPhoneRight = 175,
		ControlPhoneSelect = 176,
		ControlPhoneCancel = 177,
		ControlPhoneOption = 178,
		ControlPhoneExtraOption = 179,
		ControlPhoneScrollForward = 180,
		ControlPhoneScrollBackward = 181,
		ControlPhoneCameraFocusLock = 182,
		ControlPhoneCameraGrid = 183,
		ControlPhoneCameraSelfie = 184,
		ControlPhoneCameraDOF = 185,
		ControlPhoneCameraExpression = 186,
		ControlFrontendDown = 187,
		ControlFrontendUp = 188,
		ControlFrontendLeft = 189,
		ControlFrontendRight = 190,
		ControlFrontendRdown = 191,
		ControlFrontendRup = 192,
		ControlFrontendRleft = 193,
		ControlFrontendRright = 194,
		ControlFrontendAxisX = 195,
		ControlFrontendAxisY = 196,
		ControlFrontendRightAxisX = 197,
		ControlFrontendRightAxisY = 198,
		ControlFrontendPause = 199,
		ControlFrontendPauseAlternate = 200,
		ControlFrontendAccept = 201,
		ControlFrontendCancel = 202,
		ControlFrontendX = 203,
		ControlFrontendY = 204,
		ControlFrontendLb = 205,
		ControlFrontendRb = 206,
		ControlFrontendLt = 207,
		ControlFrontendRt = 208,
		ControlFrontendLs = 209,
		ControlFrontendRs = 210,
		ControlFrontendLeaderboard = 211,
		ControlFrontendSocialClub = 212,
		ControlFrontendSocialClubSecondary = 213,
		ControlFrontendDelete = 214,
		ControlFrontendEndscreenAccept = 215,
		ControlFrontendEndscreenExpand = 216,
		ControlFrontendSelect = 217,
		ControlScriptLeftAxisX = 218,
		ControlScriptLeftAxisY = 219,
		ControlScriptRightAxisX = 220,
		ControlScriptRightAxisY = 221,
		ControlScriptRUp = 222,
		ControlScriptRDown = 223,
		ControlScriptRLeft = 224,
		ControlScriptRRight = 225,
		ControlScriptLB = 226,
		ControlScriptRB = 227,
		ControlScriptLT = 228,
		ControlScriptRT = 229,
		ControlScriptLS = 230,
		ControlScriptRS = 231,
		ControlScriptPadUp = 232,
		ControlScriptPadDown = 233,
		ControlScriptPadLeft = 234,
		ControlScriptPadRight = 235,
		ControlScriptSelect = 236,
		ControlCursorAccept = 237,
		ControlCursorCancel = 238,
		ControlCursorX = 239,
		ControlCursorY = 240,
		ControlCursorScrollUp = 241,
		ControlCursorScrollDown = 242,
		ControlEnterCheatCode = 243,
		ControlInteractionMenu = 244,
		ControlMpTextChatAll = 245,
		ControlMpTextChatTeam = 246,
		ControlMpTextChatFriends = 247,
		ControlMpTextChatCrew = 248,
		ControlPushToTalk = 249,
		ControlCreatorLS = 250,
		ControlCreatorRS = 251,
		ControlCreatorLT = 252,
		ControlCreatorRT = 253,
		ControlCreatorMenuToggle = 254,
		ControlCreatorAccept = 255,
		ControlCreatorDelete = 256,
		ControlAttack2 = 257,
		ControlRappelJump = 258,
		ControlRappelLongJump = 259,
		ControlRappelSmashWindow = 260,
		ControlPrevWeapon = 261,
		ControlNextWeapon = 262,
		ControlMeleeAttack1 = 263,
		ControlMeleeAttack2 = 264,
		ControlWhistle = 265,
		ControlMoveLeft = 266,
		ControlMoveRight = 267,
		ControlMoveUp = 268,
		ControlMoveDown = 269,
		ControlLookLeft = 270,
		ControlLookRight = 271,
		ControlLookUp = 272,
		ControlLookDown = 273,
		ControlSniperZoomIn = 274,
		ControlSniperZoomOut = 275,
		ControlSniperZoomInAlternate = 276,
		ControlSniperZoomOutAlternate = 277,
		ControlVehicleMoveLeft = 278,
		ControlVehicleMoveRight = 279,
		ControlVehicleMoveUp = 280,
		ControlVehicleMoveDown = 281,
		ControlVehicleGunLeft = 282,
		ControlVehicleGunRight = 283,
		ControlVehicleGunUp = 284,
		ControlVehicleGunDown = 285,
		ControlVehicleLookLeft = 286,
		ControlVehicleLookRight = 287,
		ControlReplayStartStopRecording = 288,
		ControlReplayStartStopRecordingSecondary = 289,
		ControlScaledLookLeftRight = 290,
		ControlScaledLookUpDown = 291,
		ControlScaledLookUpOnly = 292,
		ControlScaledLookDownOnly = 293,
		ControlScaledLookLeftOnly = 294,
		ControlScaledLookRightOnly = 295,
		ControlReplayMarkerDelete = 296,
		ControlReplayClipDelete = 297,
		ControlReplayPause = 298,
		ControlReplayRewind = 299,
		ControlReplayFfwd = 300,
		ControlReplayNewmarker = 301,
		ControlReplayRecord = 302,
		ControlReplayScreenshot = 303,
		ControlReplayHidehud = 304,
		ControlReplayStartpoint = 305,
		ControlReplayEndpoint = 306,
		ControlReplayAdvance = 307,
		ControlReplayBack = 308,
		ControlReplayTools = 309,
		ControlReplayRestart = 310,
		ControlReplayShowhotkey = 311,
		ControlReplayCycleMarkerLeft = 312,
		ControlReplayCycleMarkerRight = 313,
		ControlReplayFOVIncrease = 314,
		ControlReplayFOVDecrease = 315,
		ControlReplayCameraUp = 316,
		ControlReplayCameraDown = 317,
		ControlReplaySave = 318,
		ControlReplayToggletime = 319,
		ControlReplayToggletips = 320,
		ControlReplayPreview = 321,
		ControlReplayToggleTimeline = 322,
		ControlReplayTimelinePickupClip = 323,
		ControlReplayTimelineDuplicateClip = 324,
		ControlReplayTimelinePlaceClip = 325,
		ControlReplayCtrl = 326,
		ControlReplayTimelineSave = 327,
		ControlReplayPreviewAudio = 328,
		ControlVehicleDriveLook = 329,
		ControlVehicleDriveLook2 = 330,
		ControlVehicleFlyAttack2 = 331,
		ControlRadioWheelUpDown = 332,
		ControlRadioWheelLeftRight = 333,
		ControlVehicleSlowMoUpDown = 334,
		ControlVehicleSlowMoUpOnly = 335,
		ControlVehicleSlowMoDownOnly = 336,
		ControlMapPointOfInterest = 337,
	};
	enum FlagID {
		PED_FLAG_CAN_FLY_THRU_WINDSCREEN = 32,
		PED_FLAG_NO_COLLISION = 52,
		PED_FLAG_NO_COLLIDE = 62,
		PED_FLAG_DEAD = 71,
		PED_FLAG_SUPER_DEAD = 73,
		PED_FLAG_IS_AIMING = 78,
		PED_FLAG_DRUNK = 100,
		PED_FLAG_NM_MESSAGE_466 = 125,
		PED_FLAG_INJURED_LIMP = 166,
		PED_FLAG_INJURED_LIMP_2 = 170,
		PED_FLAG_INJURED_DOWN = 187,
		PED_FLAG_SHRINK = 223,
		PED_FLAG_NO_WRITHE = 281,
		PED_FLAG_FREEZE = 292,
		PED_FLAG_IS_STILL = 301,
		PED_FLAG_ALPHA = 410,
	};
}